repoURL: "https://github.com/jamiekariuki/DevSecOps-helm-charts.git"
targetRevision: main

app:
  path: app
  values:
    dev: values-dev.yaml
    stage: values-stage.yaml
    prod: values-prod.yaml

########################################################
#                      controllers   
########################################################

prometheus:
  name: prometheus
  namespace: monitoring
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: "65.1.0"
  syncWaves: "-10"
 
gateway:
  name: gateway-api
  namespace: envoy-gateway-system
  repoURL: oci://docker.io/envoyproxy/gateway-helm
  chart: gateway-helm
  version: "v1.6.1"
  syncWaves: "-10"
   
certManager:
  name: cert-manager
  namespace: cert-manager
  repoURL: oci://quay.io/jetstack/charts/cert-manager
  chart: cert-manager
  version: "v1.19.2"
  syncWaves: "-10"