apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: ${var.ENV_PREFIX}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: ${module.db.db_instance_master_user_secret_arn}
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: ${module.db.db_instance_master_user_secret_arn}
      property: password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: ${module.db.db_instance_master_user_secret_arn
      property: dbname
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: ${module.db.db_instance_master_user_secret_arn}
      property: host
  - secretKey: POSTGRES_PORT
    remoteRef:
      key: ${module.db.db_instance_master_user_secret_arn}
      property: port
