apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore
  namespace: ${var.ENV_PREFIX}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${var.region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${var.service_account_name}
            namespace: ${var.ENV_PREFIX}
