apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.prometheusCrd.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.prometheusCrd.syncWaves | quote }}
    argocd.argoproj.io/hook: {{ .Values.prometheusCrd.hook }}
spec:
  project: default
  source:
    repoURL: {{ .Values.prometheusCrd.repoURL }}
    chart: {{ .Values.prometheusCrd.chart }}
    targetRevision: {{ .Values.prometheusCrd.version }}
    helm:
      values: |
        prometheus-operator:
          enabled: true
          manageCrds: true
        
        prometheus:
          enabled: true
        
        grafana:
          enabled: true
          adminPassword: "prometheus"
          grafana.ini:
            server:
              root_url: http://grafana.example.com
              serve_from_sub_path: true
        
        alertmanager:
          enabled: true
        
        nodeExporter:
          enabled: true
        
        kubeStateMetrics:
          enabled: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.prometheusCrd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m







