repoURL: "https://github.com/jamiekariuki/DevSecOps-helm-charts.git"
targetRevision: main

app:
  path: app
  values:
    dev: values-dev.yaml
    stage: values-stage.yaml
    prod: values-prod.yaml

prometheus:
  name: prometheus
  path: monitoring/prometheus
  syncWave: "-9"

prometheusCrd:
  name: prometheusCrd
  path: monitoring/prometheus-crd
  syncWave: "-10"


 #chart 