repoURL: "https://github.com/jamiekariuki/DevSecOps-helm-charts.git"
targetRevision: main

#=======================================================
#                      app   
#======================================================

app:
  path: app
  values:
    dev: values-dev.yaml
    stage: values-stage.yaml
    prod: values-prod.yaml
  hook: PostSync  
  syncWaves: "1"  

#=======================================================
#                      controllers & CRDs 
#=======================================================

prometheusCrd:
  name: prometheus-crd
  namespace: monitoring
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: "65.1.0"
  hook: PreSync
  syncWaves: "-10"

gatewayCrd:
  name: gateway-api-crd
  namespace: envoy-gateway-system
  repoURL: oci://docker.io/envoyproxy/gateway-helm
  chart: gateway-helm
  version: "v1.6.1"
  hook: PreSync
  syncWaves: "-10"
   
certManagerCrd:
  name: cert-manager-crd
  namespace: cert-manager
  repoURL: oci://quay.io/jetstack/charts/cert-manager
  chart: cert-manager
  version: "v1.19.2"
  hook: PreSync
  syncWaves: "-10"


#=======================================================
#                      resources  
#======================================================

gatewayCr:
  name: gateway-api-cr
  namespace: gateway
  path: gateway
  hook: Sync
  syncWaves: "-9" #2nd

certManagerCr:
  name: cert-manager-cr
  path: cert-manager
  hook: Sync
  syncWaves: "-10" #1st

prometheusCr:
  name: prometheus-cr
  path: prometheus
  hook: Sync
  syncWaves: "-8"