repoURL: "https://github.com/jamiekariuki/DevSecOps-helm-charts.git"
targetRevision: main
#=======================================================
#                      app   
#======================================================
app:
  path: app
  values:
    dev: values-dev.yaml
    stage: values-stage.yaml
    prod: values-prod.yaml
  hook: PostSync
  syncWaves: "1"
#=======================================================
#                      controllers & CRDs 
#=======================================================
prometheusCrd:
  name: prometheus-crd
  namespace: monitoring
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: "80.3.0"
  hook: PreSync
  syncWaves: "-9"
gatewayCrd:
  name: gateway-api-crd
  namespace: envoy-gateway-system
  repoURL: oci://docker.io/envoyproxy/gateway-helm
  chart: gateway-helm
  version: "v1.6.1"
  hook: PreSync
  syncWaves: "-10"
certManagerCrd:
  name: cert-manager-crd
  namespace: cert-manager
  repoURL: oci://quay.io/jetstack/charts/cert-manager
  chart: cert-manager
  version: "v1.19.2"
  hook: PreSync
  syncWaves: "-10"
lokiCrd:
  name: loki-crd
  namespace: monitoring
  repoURL: https://grafana.github.io/helm-charts
  chart: loki
  version: "6.49.0" #6.29
  hook: PreSync
  syncWaves: "-10"
promtailCrd:
  name: promtail-crd
  namespace: monitoring
  repoURL: https://grafana.github.io/helm-charts
  chart: promtail
  version: "6.17.1"
  hook: PreSync
  syncWaves: "-10"
esoCrd:
  name: eso-crd
  namespace: external-secrets
  repoURL: https://charts.external-secrets.io
  chart: external-secrets
  version: "v1.1.0"
  hook: PreSync
  syncWaves: "-10"
  serviceAccount:
    name: external-secrets-sa
    irsaArn: arn:aws:iam::466872246229:role/external-secrets-2026010221270320570000000f
#=======================================================
#                      resources                       
#=======================================================
gatewayCr:
  name: gateway-api-cr
  namespace: gateway
  path: gateway
  hook: Sync
  syncWaves: "-9" #2nd
certManagerCr:
  name: cert-manager-cr
  path: cert-manager
  hook: Sync
  syncWaves: "-10" #1st
prometheusCr:
  name: prometheus-cr
  path: prometheus
  hook: Sync
  syncWaves: "-1"
argocdCr:
  name: argocd-cr
  path: argocd
  hook: Sync
  syncWaves: "-8"
esoCr:
  name: eso-cr
  path: eso
  hook: Sync
  syncWaves: "-8"
