name: argo Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to destroy"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - stage
        - prod

env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: argocd
      run: |
        terraform init -upgrade \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=networking/terraform.tfstate" \
          -backend-config="region=${{ secrets.REGION }}" \
          -backend-config="dynamodb_table=terraform-locks" \
          -backend-config="encrypt=true"

    - name: Select Terraform Workspace
      working-directory: argocd
      run: terraform workspace select -or-create=true $ENVIRONMENT

    - name: Terraform Destroy
      working-directory: argocd
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
        ENV_PREFIX: ${{ env.ENVIRONMENT }}
      run: |
        terraform destroy -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" \
