name: Terraform

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - stage
        - prod

env:
  ENVIRONMENT: dev #${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref_name == 'release/dev' && 'dev' || github.ref_name == 'release/stage' && 'stage' || 'prod') }}

jobs:
  terraform-filter:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          changed:
            - 'infrastructure/terraform/**'

  argocd-filter:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          changed:
            - 'infrastructure/argo-cd/**'

  # Step 1: Terraform Apply
  terraform:
    runs-on: ubuntu-latest
    needs: terraform-filter
    if: needs.terraform-filter.outputs.changed == 'true'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/terraform
      run: terraform init -upgrade

    - name: Select Terraform Workspace
      working-directory: infrastructure/terraform
      run: terraform workspace select -or-create=true $ENVIRONMENT

    - name: Terraform Apply
      working-directory: infrastructure/terraform
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACCOUNT_NAME: ${{ secrets.SERVICE_ACCOUNT_NAME }}
        ENV_PREFIX: ${{ env.ENVIRONMENT }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" \
          -var="db_username=$DB_USERNAME" \
          -var="db_name=$DB_NAME" \
          -var="service_account_name=$SERVICE_ACCOUNT_NAME" \
          -var="ENV_PREFIX=$ENV_PREFIX"

  # Step 2: configure argocd
  Argocd:
    runs-on: ubuntu-latest
    needs: argocd-filter
    if: |
      needs.argocd-filter.outputs.changed == 'true' &&
      (
        needs.terraform.outputs.result == 'success' ||
        needs.terraform-filter.outputs.changed == 'false'
      )

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: infrastructure/argo-cd
      run: terraform init -upgrade

    - name: Terraform Apply
      working-directory: infrastructure/argo-cd
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
          -var="cluster_name=$CLUSTER_NAME" 
