name: State bucket

on:
  workflow_dispatch:


jobs:
  # Step 1: Terraform Apply
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform Init
      working-directory: state-bucket
      run: terraform init -upgrade

    - name: Terraform Apply
      working-directory: state-bucket
      env:
        TF_IN_AUTOMATION: true
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
      run: |
        terraform apply -auto-approve -input=false \
          -var="aws_account_id=$AWS_ACCOUNT_ID" \
          -var="region=$REGION" \
